apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-hostname-response-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod-hostname-response
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: autoscaling.enabled
        value: "true"
    chart: response-hostname
    repoURL: https://helm3.brodul.org
    targetRevision: 0.1.6
  syncPolicy:
      automated: {}
      syncOptions:
        - CreateNamespace=true
